### PR TITLE
feature: add second version of game

### PR DESCRIPTION
**Pull request by Rupesh-Darimisetti**
A new version of game was added with improved logic, design and added nice music, navigation bar.

You can take a look at the game window from here

tic_tac_toe_v2

### CODE REVIEW

**Comment by Rupesh-Darimisetti** [comment]
if you accept my pull request please add a label with **hacktoberfest-accepted** and merge it.

**Comment by Rupesh-Darimisetti** [comment]
@Keertijanm or @guptasakshi28 please review this version of game

**Comment by Keertijanm** [comment]
I am reviewing

**Comment by Rupesh-Darimisetti** [comment]
Please add this project to hactoberfest and add hactoberfest accepted label to this pull request.

**Pull request merged**
